<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8e6802ed4898b93846829988e2145341
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Dir\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Dir\\' => 
        array (
            0 => __DIR__ . '/..' . '/hisheng/dir/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8e6802ed4898b93846829988e2145341::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8e6802ed4898b93846829988e2145341::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
